### ISSUE TITLE
AttributeError: type object 'MessageType' has no attribute 'application_command'

### ISSUE THREAD

**Issue by codeman1o1** [Skelmis/Discord-Anti-Spam#92]
**Describe the bug**
When I send a message it gives this error:

```py
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\client.py", line 415, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\me\Desktop\Glorious\main.py", line 190, in on_message
    await bot.handler.propagate(message)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\anti_spam_handler.py", line 71, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\anti_spam_handler.py", line 311, in propagate
    main_return = await self.core.propagate(message, guild=guild)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\core.py", line 70, in propagate
    guild_r = await self.propagate_user(message, guild)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\core.py", line 114, in propagate_user
    message: Message = await self.handler.lib_handler.create_message(
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\antispam\libs\dpy.py", line 217, in create_message
    if message.is_system():
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\message.py", line 1010, in is_system
    MessageType.application_command,
AttributeError: type object 'MessageType' has no attribute 'application_command'
```

**To Reproduce**
My code is as following:
```py
from nextcord.ext import commands
from antispam import AntiSpamHandler, Options
from antispam.enums import Library

bot = commands.Bot(...)

bot.handler = AntiSpamHandler(
    bot,
    library=Library.NEXTCORD,
    options=Options(use_timeouts=True, delete_zero_width_chars=True),
)

@bot.event
async def on_message(message):
    await bot.handler.propagate(message)
    await bot.process_commands(message)
```

**Expected behaviour**
Not giving an error

**Screenshots**

**Enviroment(please complete the following information):**
 - OS: Windows
 - Package Version: 1.2.8

**Additional context**

**Comment by Skelmis** [comment]
What version of nextcord are you on?

**Comment by codeman1o1** [comment]
Okay... I was on Version 2.0.0a7 when I had the error, but when I upgraded to 2.0.0a8 it fixed itself.
I just looked in the changelog for 2.0.0a8 and I think the error was patched: [_Fix bug where calling is_system would error_](https://github.com/nextcord/nextcord/releases/tag/2.0.0a8)

**Comment by Skelmis** [comment]
Yea, I remember fixing the is system bug. Glad its all fixed, for reference next time you should ask over in Nextcord as its a library issue, not with my package.
